/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'Lab3_LuisCordova_23012122.Debug+ARMCM4' 
 * Target:  'Debug+ARMCM4' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM4.h"



#endif /* RTE_COMPONENTS_H */
